from Person import Person
from Booking import *


event_1 = SportEvent(1, "Football match", "2024.12.01", "Stadium A", 500,
                     200, 50, "Sector A")
print(event_1)
print(event_1.order_food('cola'))
print(event_1.order_souvenirs('cap'))
print(event_1)
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
event_2 = Concert(2, "Rock Concert", "2024.12.05", "Arena B", 800, 300,
                  100, "Rock Band", "Rock")
print(event_2)
print(event_2.get_promo_code('Autumn'))
print(event_2)
print(event_2.get_promo_code('APT'))
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
event_3 = Cinema(3, "Going to the cinema", "2024.11.12", "CARO", 450, 10,
                 25, "2D", 16)
print(event_3)
print(event_3.order_for_cinema('chips'))
print(event_3.order_for_cinema('beer'))
print(event_3)
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
event_4 = Theatre(3, "Romeo and Juliet", "2025.12.10", "The Big theatre", 7500,
                  200, 350, 'tragedy')
print(event_4)
print(event_4.get_the_booklet('Romeo and Juliet'))
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
person_1 = Person("Alice", 25, "alice@example.com", "1234567890")
person_2 = Person("Sasha", 24, "ce@example.com", "1237890")
booking = Booking()
print(booking.create(person_1, event_1, 129))
print(booking.create(person_2, event_1, 129))
print(booking.create(person_1, event_2, 129))
print("Read all:")
print(booking.read_all())
print("Read by id:")
print(booking.read_by_id(1))
print(booking.update(2, 150))
print(booking.delete(1))
print("Bookings in JSON format:")
print(booking.to_json())
print("\nBookings in XML format:")
print(booking.to_xml())
